services:
  dagdegas:
    build: .
    container_name: dagdegas-app
    ports:
      - "10001:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # Aggiungi qui eventuali variabili d'ambiente necessarie
